version: '2'
services:
  web:
    build:
      context: .
      dockerfile: .docker/api-web.dockerfile
    environment:
      WEBROOT: /var/www/html/public
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - "81:80"
    networks:
      - api-network
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: .docker/api-db.dockerfile
    networks:
      - api-network
    ports:
      - "3307:3306"
  cache:
    build:
      context: .
      dockerfile: .docker/api-cache.dockerfile
    networks:
      - api-network
networks:
  api-network:
    driver: bridge